### ISSUE TITLE
Binding exception when using delegatinghandler from a library

### ISSUE THREAD

**Issue by stevengopmo** [dotnetjunkie/solidservices#21]
Hi,

I'm sure this is something fundamental but I get the following error when I use the QueryDelegatingHandler from a library dll instead of directly in my webapi projects.

	System.AggregateException: One or more errors occurred. ---> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'object' does not contain a definition for 'HandleAsync'
	   at CallSite.Target(Closure , CallSite , Object , Object )
	   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
	   at goPMO.Common.WebApi.QueryDelegatingHandler.<SendAsync>d__3.MoveNext() in C:\projects\gopmo-common\source\goPMO.Common.WebApi\QueryDelegatingHandler.cs:line 67
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Web.Http.Cors.CorsMessageHandler.<SendAsync>d__2.MoveNext()
	   --- End of inner exception stack trace ---
	   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
	   at System.Threading.Tasks.Task`1.get_Result()
	   at goPMO.Common.WebApi.Security.DummyAuthenticationHandler.<>c.<SendAsync>b__2_0(Task`1 task) in C:\projects\gopmo-common\source\goPMO.Common.WebApi\Security\DummyAuthenticationHandler.cs:line 28
	   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
	   at System.Threading.Tasks.Task.Execute()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Web.Http.HttpServer.<SendAsync>d__24.MoveNext()
	---> (Inner Exception #0) Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'object' does not contain a definition for 'HandleAsync'
	   at CallSite.Target(Closure , CallSite , Object , Object )
	   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
	   at goPMO.Common.WebApi.QueryDelegatingHandler.<SendAsync>d__3.MoveNext() in C:\projects\gopmo-common\source\goPMO.Common.WebApi\QueryDelegatingHandler.cs:line 67
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Web.Http.Cors.CorsMessageHandler.<SendAsync>d__2.MoveNext()<---

The same exact code works fantastic when included in the actual WebApi.  At first I thought it had something to do with types e.g. where type is in thisassembly vs. whatever type I actually asked for but that doesn't appear to be the case.  

For reference the code that is erroring is 

            try
            {
                var query = DeserializeQuery(request, queryData, info.QueryType);
                var result = await handler.HandleAsync(query);
                return HttpResponseMessageExtensions.FromResult(request, result);
            }
            catch (Exception exception)
            {
                var response = WebApiErrorResponseBuilder.CreateErrorResponseOrNull(exception, request);
                if (response != null)
                    return response;

                throw;
            }

Line 67 from the stack trace is the `throw;` line.  Obviously the error is occuring at the ' var result = await handler.HandleAsync(query);' where query is an object instead of the type I want.

Any thoughts?

**Comment by BrettJaner** [comment]
Try casting the query object instance as dynamic.

    dynamic query = DeserializeQuery(request, queryData, info.QueryType);

**Comment by stevengopmo** [comment]
unfortunately no luck same exact error.

**Comment by stevengopmo** [comment]
just verified that I get the same with DelegatingCommandHandler (expected).  It already had the `dynamic command = DeserializeCommand(request, commandData, info.CommandType);`

**Comment by BrettJaner** [comment]
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'object' does not contain a definition for 'HandleAsync'

How are you getting your handler instance?  The exception message is saying the handler is of type 'object'.  The type in the message should be the type of your handler.  Maybe a problem with container registration?

**Comment by stevengopmo** [comment]
var assembliesToScan = new[]
            {
                typeof(Project).Assembly,
            };

            container.Register(typeof(IHandleCommandAsync<>),
                assembliesToScan);
I left out the decorators for brevity.  Why does it work when delegating handlers are copied to local code with no other code changes?

**Comment by dotnetjunkie** [comment]
Is your outer-most decorator internal?

**Comment by stevengopmo** [comment]
yes...  drat.  so all decorators must be public to operate in this fashion?

**Comment by stevengopmo** [comment]
just to confirm, that was definitely it.  this is why you are my hero!

still, it seems that IF my factory is just the `container.getinstance` method why does the common class need to know about the internal decorator?  Shouldn't it just know that it implements IHandleQueriesAsync? or is this because dynamic?

**Comment by dotnetjunkie** [comment]
Well, this has to do with how the C# dynamic binder works. If will be unable to bind to a method of an internal type. To me this feels like a quirk in the dynamic binder implementation, because even if the type is internal, the defined interface is public and hence its HandleAsync method is publically accessible, and the dynamic binder should be able to find out. But unfortunately, it doesn't :'(

There are two alternative approaches to using `dynamic`:

- You can use 'old-fashioned' reflection. Problem with this approach however is that when HandleAsync throws an exception, it gets wrapped in a `TargetInvocationException`, which makes it harder to handle exceptions appropriately.
- You can create a generic wrapper class, depending on `IHandleCommandAsync<>`, and implements a non-generic interface. You can use Simple Injector to resolve an instance of that wrapper, cast it to the non-generic interface and call its Handle method.

**Comment by stevengopmo** [comment]
so...  would just ensuring that outer most decorator is public work?  Not suggesting this is a great idea, just curious.  I think it probably would given that it's only really that top-level decorator that is called, the rest is internal implementation details right?

**Comment by stevengopmo** [comment]
Thanks as always @dotnetjunkie and thanks @BrettJaner for responding
